[features]
seeds = false
skip-lint = false
[programs.localnet]
string_saver = "B5siGtoGsZmrTdBkeja6tv4YG8mHpPQmsNXp2FhYWkJT"
[programs.devnet]
string_saver = "B5siGtoGsZmrTdBkeja6tv4YG8mHpPQmsNXp2FhYWkJT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
